### ISSUE TITLE
Порядок установки

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/WebPrinter#1]
Что то похожее было с драйвером для Webkassa
реталикс сейчас умеет использовать только имя подключения "SHTRIH-M-OPOS-1"(и SHTRIH-M-OPOS-2)
что бы использовать WebPrinter нам нужно ссылку на длл OposWebPrinter.FiscalPrinter из ветки реестра WebPrinter-OPOS-1
перезаписывать вручную в ветку реестра SHTRIH-M-OPOS-1

Можно сделать что бы при установке WebPrinter ссылка на OposWebPrinter.FiscalPrinter записывалась и в ветку реестра SHTRIH-M-OPOS-1?

![11](https://github.com/VitalyKravtsov2016/WebPrinter/assets/112083079/9f2ec5a9-304f-4824-9913-84b0e470894c)
![22](https://github.com/VitalyKravtsov2016/WebPrinter/assets/112083079/ecb770c5-8cd2-412b-9ae0-eac78a4bfb03)

**Comment by VitalyKravtsov2016** [comment]
Да, сейчас сделаю.
