### ISSUE TITLE
проблема с подключением на боевой принтер

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/WebPrinter#17]
инфо проходит, а дальше ошибка. непонятно в чем причина
GET: http://192.168.1.194:9090/info/

[05.02.2024 15:34:32.533 ] [00005444] [ERROR] OPOS_E_FAILURE, 0, "'' is not a valid integer value"

[SHTRIH-M-OPOS-1_2024.02.05 (2).log](https://github.com/VitalyKravtsov2016/WebPrinter/files/14163949/SHTRIH-M-OPOS-1_2024.02.05.2.log)

**Comment by VitalyKravtsov2016** [comment]
Поменяли тип поля cashbox_number в ответе Info.
Был тип Integer, стал текст:
Было: "cashbox_number": 1 в версии applet_version = 0300
Стало: "cashbox_number": "" в версии applet_version = 0302
Сейчас поправлю.
