### ISSUE TITLE
Блокировка установки

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/WebPrinter#2]
на предыдущей версии этого предупреждения не было

![1](https://github.com/VitalyKravtsov2016/WebPrinter/assets/112083079/94c3fd5d-3137-4bf5-83c4-431835f6e779)
[20240118.zip](https://github.com/VitalyKravtsov2016/WebPrinter/files/13973450/20240118.zip)

**Comment by VitalyKravtsov2016** [comment]
Что за операционная система?

**Comment by Dafafgh** [comment]
![2](https://github.com/VitalyKravtsov2016/WebPrinter/assets/112083079/6038023b-2071-4fec-97f2-5ee48936254c)

**Comment by VitalyKravtsov2016** [comment]
Там разница была в исталляторе. Была 5.5.9, стала 6.2.1. 
Просто дома и на рабочем компе стоят разные версии инсталлятора InnoSetup. 
Собрал старым инсталлятором:
https://cloud.mail.ru/public/rZn4/Wqxub74AX
