### ISSUE TITLE
Скидка на чек

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/WebPrinter#21]
у нас появился тип скидки на чек. можно это тоже добавить?

[22.02.2024 11:51:11.725 ] [00005236] [DEBUG] ToleFiscalPrinter.PrintRecSubtotalAdjustment(1, 'Округление', 0.8)
[22.02.2024 11:51:11.726 ] [00005236] [DEBUG] ToleFiscalPrinter.PrintRecSubtotalAdjustment(1, 'Округление', 0.8)=0

discount":0,"discount_percent":0,

{"qr_code":"","number":1,"receipt_type":"order","products":[{"name":"PUMP 1:АИ92","barcode":"","amount":5556,"units":1,"unit_name":"л","price":10000080,"product_price":1800000,"vat":1071437,"vat_percent":12,"discount":0,"discount_percent":0,"other":0,"labels":[],"class_code":"02710001005000000","package_code":0,"owner_type":0,"comission_info":{"inn":"","pinfl":""}}],"time":"2024-02-22 13:51:08","cashier":"ҲўғўровҚ ЎғўбекҒ","received_cash":10000000,"change":0,"received_card":0,"open_cashbox":false,"send_email":false,"banners":[{"type":"text","data":"Operator: ҲўғўровҚ ЎғўбекҒ","Cut":false},{"type":"text","data":"ID:       1081 ","Cut":false}]}

[SHTRIH-M-OPOS-1_2024.02.22.log](https://github.com/VitalyKravtsov2016/WebPrinter/files/14371523/SHTRIH-M-OPOS-1_2024.02.22.log)

**Comment by Dafafgh** [comment]
можно узнать примерные сроки? эта доработка на текущий момент самая наиважнейшая. ждем ее для изменения алгоритма расчета на пилотной азс

**Comment by VitalyKravtsov2016** [comment]
Сегодня сделаю, постараюсь побыстрее.

**Comment by Dafafgh** [comment]
Спасибо

**Comment by VitalyKravtsov2016** [comment]
В этом ФР нет округления, поэтому скидки на чек не работают. 
В UPOS для класса фискального принтера есть свойства:
CapSubAmountAdjustment и CapSubPercentAdjustment,
которые говорят, возможно ли скидки на подитог чека. 
Но приложение эти свойства не анализирует. 
Варианты решения:
1. Установить CapSubAmountAdjustment и CapSubPercentAdjustment в False и доработать приложение. 
2. Либо раскидывать скидку по позициям, либо применить к последней позиции.

**Comment by Dafafgh** [comment]
1. что бы приложение смотрело по флагу CapSubAmountAdjustment возможна ли вообще скидка на подытог чека? и если невозможна переделывало скидку в скидку на линию?

**Comment by VitalyKravtsov2016** [comment]
Да
