### ISSUE TITLE
какая то ошибка на изъятии

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/WebPrinter#22]
мы стали работать с дробной суммой. на стенде при внесении fbox вернули ошибку, не понятно из-за чего

[22.02.2024 12:28:46.788 ] [00001756] [DEBUG] GET: http://fbox.ngrok.io/zreport/open/?time=2024-02-22%2014:28:44
[22.02.2024 12:28:46.788 ] [00001756] [DEBUG] => 
[22.02.2024 12:28:47.646 ] [00001756] [DEBUG] <= {
  "data": null,
  "error": {
    "code": 36912,
    "message": "ERROR_ZREPORT_IS_ALREADY_OPEN",
    "data": "ERROR_ZREPORT_IS_ALREADY_OPEN\n  ERROR_ZREPORT_IS_ALREADY_OPEN\n"
  },
  "is_success": false
}

[SHTRIH-M-OPOS-1_2024.02.22.log](https://github.com/VitalyKravtsov2016/WebPrinter/files/14372191/SHTRIH-M-OPOS-1_2024.02.22.log)

**Comment by Dafafgh** [comment]
получается смена не открывается автоматом при продаже?
    "code": 36909,
    "message": "ERROR_ZREPORT_IS_NOT_OPEN",
    "data": "ERROR_ZREPORT_IS_NOT_OPEN\n  ERROR_ZREPORT_IS_NOT_OPEN\n"

[SHTRIH-M-OPOS-1_2024.02.22.log](https://github.com/VitalyKravtsov2016/WebPrinter/files/14372883/SHTRIH-M-OPOS-1_2024.02.22.log)

**Comment by VitalyKravtsov2016** [comment]
Непонятным образом работает определение открыта ли смена. 
Драйвер запрашивает через GET: http://fbox.ngrok.io/zreport/info/:
[22.02.2024 12:24:18.734 ] [00001756] [DEBUG] GET: http://fbox.ngrok.io/zreport/info/
Получает в ответе, что  "open_time": "", то есть смена не открыта.
Но при попытке открыть смену выдается ошибка:
[22.02.2024 12:28:46.788 ] [00001756] [DEBUG] GET: http://fbox.ngrok.io/zreport/open/?time=2024-02-22%2014:28:44
[22.02.2024 12:28:47.646 ] [00001756] [DEBUG] <= {
  "data": null,
  "error": {
    "code": 36912,
    "message": "ERROR_ZREPORT_IS_ALREADY_OPEN",
    "data": "ERROR_ZREPORT_IS_ALREADY_OPEN\n  ERROR_ZREPORT_IS_ALREADY_OPEN\n"
  },
  "is_success": false
}
Добавлю обработку ошибок ERROR_ZREPORT_IS_ALREADY_OPEN и ERROR_ZREPORT_IS_NOT_OPEN.
